# Simplified Portainer Docker Compose for Betting SRL
# Replace 'yourusername' with your actual GitHub username
# This version builds from the main branch and exposes the app directly on port 5000

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: betting-srl-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: betting_srl
      POSTGRES_USER: betting_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - betting-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U betting_user -d betting_srl"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application Server
  app:
    build:
      context: https://github.com/yourusername/betting-srl.git#main
      dockerfile: Dockerfile
    image: betting-srl:latest
    container_name: betting-srl-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://betting_user:${POSTGRES_PASSWORD:-secure_password_123}@postgres:5432/betting_srl
      SESSION_SECRET: ${SESSION_SECRET:-change-this-super-secret-session-key-in-production}
      GNEWS_API_KEY: ${GNEWS_API_KEY:-}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY:-}
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
      - assets:/app/attached_assets
    networks:
      - betting-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  uploads:
    driver: local
  assets:
    driver: local

networks:
  betting-network:
    driver: bridge

# Usage Instructions:
# 1. Replace 'yourusername' with your GitHub username
# 2. Set environment variables in Portainer:
#    - POSTGRES_PASSWORD (required)
#    - SESSION_SECRET (required)
#    - GNEWS_API_KEY (optional)
#    - SENDGRID_API_KEY (optional)
# 3. Deploy the stack
# 4. Access your app at http://your-server:5000
# 5. Initialize database: docker exec betting-srl-app npm run db:push